# Generated by Django 5.2.14 on 2026-08-21 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "frameworks",
            "0004_frameworkversion_ck_fw_version_effective_date_range_and_more",
        ),
        ("periods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FROZEN", "Frozen")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("snapshot_frozen_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_report_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "framework_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_runs",
                        to="frameworks.frameworkversion",
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_runs",
                        to="periods.reportingperiod",
                    ),
                ),
            ],
            options={
                "db_table": "report_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FrameworkSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_framework_id", models.UUIDField()),
                ("source_framework_version_id", models.UUIDField()),
                ("framework_code", models.CharField(max_length=50)),
                ("framework_name", models.CharField(max_length=255)),
                ("version_code", models.CharField(max_length=100)),
                (
                    "version_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("frozen_at", models.DateTimeField()),
                (
                    "report_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="framework_snapshot",
                        to="reporting.reportrun",
                    ),
                ),
            ],
            options={
                "db_table": "framework_snapshots",
            },
        ),
        migrations.CreateModel(
            name="SnapshotNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_node_id", models.UUIDField(blank=True, null=True)),
                ("code", models.CharField(max_length=150)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("instructions", models.TextField(blank=True, default="")),
                ("node_type", models.CharField(max_length=30)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("depth", models.PositiveIntegerField(default=0)),
                ("path", models.TextField(blank=True, default="")),
                (
                    "response_format",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("is_answerable", models.BooleanField(default=False)),
                ("is_core", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="reporting.snapshotnode",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="reporting.frameworksnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "report_snapshot_nodes",
                "ordering": ["path", "display_order", "code", "id"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_mapping_id", models.UUIDField(blank=True, null=True)),
                ("source_datapoint_id", models.UUIDField(blank=True, null=True)),
                ("canonical_datapoint_code", models.CharField(max_length=255)),
                (
                    "mapping_type",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "aggregation",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("transform_expression", models.TextField(blank=True, default="")),
                ("is_primary", models.BooleanField(default=False)),
                ("confidence", models.CharField(blank=True, default="", max_length=20)),
                ("mapping_note", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mappings",
                        to="reporting.snapshotnode",
                    ),
                ),
            ],
            options={
                "db_table": "report_snapshot_mappings",
                "ordering": [
                    "snapshot_node",
                    "display_order",
                    "canonical_datapoint_code",
                    "id",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(
                fields=["reporting_period"], name="idx_report_run_period"
            ),
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(
                fields=["framework_version"], name="idx_report_run_fw_version"
            ),
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(fields=["status"], name="idx_report_run_status"),
        ),
        migrations.AddIndex(
            model_name="snapshotnode",
            index=models.Index(
                fields=["snapshot", "parent"], name="idx_snapshot_node_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshotnode",
            index=models.Index(
                fields=["snapshot", "path"], name="idx_snapshot_node_path"
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshotnode",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "code"), name="uq_snapshot_node_code"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshotmapping",
            index=models.Index(
                fields=["snapshot_node"], name="idx_snapshot_mapping_node"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshotmapping",
            index=models.Index(
                fields=["canonical_datapoint_code"], name="idx_snapshot_mapping_dp_code"
            ),
        ),
    ]
