# Generated by Django 5.2.14 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_department_alter_company_options_and_more"),
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportrun",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_runs",
                to="companies.company",
            ),
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(fields=["company"], name="idx_report_run_company"),
        ),
    ]
