# Generated by Django 5.2.14 on 2026-08-05 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('period_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('HALF_YEARLY', 'Half Yearly'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('is_baseline_year', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='periods.reportingperiod')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['period_type'], name='periods_rep_period__9deeda_idx'), models.Index(fields=['status'], name='periods_rep_status_432916_idx'), models.Index(fields=['start_date', 'end_date'], name='periods_rep_start_d_ac8067_idx'), models.Index(fields=['is_baseline_year'], name='periods_rep_is_base_6c0b1b_idx'), models.Index(fields=['parent'], name='periods_rep_parent__c165fb_idx')],
            },
        ),
    ]
