# Generated by Django 5.2.14 on 2026-08-18 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable machine-readable framework code.', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'frameworks',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_code', models.CharField(help_text='Stable version identifier.', max_length=100)),
                ('version_name', models.CharField(blank=True, default='', max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='frameworks.framework')),
            ],
            options={
                'db_table': 'framework_versions',
                'ordering': ['framework__code', 'version_code'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('node_type', models.CharField(choices=[('SECTION', 'Section'), ('SUBSECTION', 'Subsection'), ('DISCLOSURE', 'Disclosure'), ('INDICATOR', 'Indicator'), ('SUBINDICATOR', 'Subindicator')], max_length=30)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField(default=0, editable=False)),
                ('path', models.TextField(blank=True, editable=False)),
                ('response_format', models.CharField(blank=True, default='', max_length=30)),
                ('is_answerable', models.BooleanField(default=False)),
                ('is_core', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='frameworks.frameworknode')),
                ('framework_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='frameworks.frameworkversion')),
            ],
            options={
                'db_table': 'framework_nodes',
                'ordering': ['framework_version', 'path', 'display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='frameworkversion',
            constraint=models.UniqueConstraint(fields=('framework', 'version_code'), name='uq_framework_version_code'),
        ),
        migrations.AddIndex(
            model_name='frameworknode',
            index=models.Index(fields=['framework_version', 'parent'], name='idx_fw_node_parent'),
        ),
        migrations.AddIndex(
            model_name='frameworknode',
            index=models.Index(fields=['framework_version', 'display_order'], name='idx_fw_node_order'),
        ),
        migrations.AddIndex(
            model_name='frameworknode',
            index=models.Index(fields=['path'], name='idx_fw_node_path'),
        ),
        migrations.AddConstraint(
            model_name='frameworknode',
            constraint=models.UniqueConstraint(fields=('framework_version', 'code'), name='uq_framework_node_code_per_version'),
        ),
    ]
