# Generated by Django 5.2.14 on 2026-08-18 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0001_initial'),
        ('frameworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatapointMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping_type', models.CharField(choices=[('DIRECT', 'Direct'), ('NARRATIVE', 'Narrative / Manual'), ('CALCULATED', 'Calculated / Derived')], default='DIRECT', max_length=30)),
                ('aggregation', models.CharField(choices=[('NONE', 'None'), ('SUM', 'Sum'), ('AVG', 'Average'), ('LATEST', 'Latest'), ('COUNT', 'Count')], default='NONE', max_length=20)),
                ('transform_expression', models.TextField(blank=True, default='', help_text='Optional future transformation metadata. M7 does not execute calculations.')),
                ('is_primary', models.BooleanField(default=False)),
                ('confidence', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROVISIONAL', 'Provisional')], default='PROVISIONAL', max_length=20)),
                ('mapping_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('datapoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='framework_mappings', to='datapoints.datapoint')),
                ('framework_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datapoint_mappings', to='frameworks.frameworknode')),
            ],
            options={
                'db_table': 'datapoint_mappings',
                'indexes': [models.Index(fields=['framework_node'], name='idx_mapping_framework_node'), models.Index(fields=['datapoint'], name='idx_mapping_datapoint'), models.Index(fields=['confidence'], name='idx_mapping_confidence')],
                'constraints': [models.UniqueConstraint(fields=('framework_node', 'datapoint'), name='uq_framework_node_datapoint'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('framework_node',), name='uq_primary_mapping_per_node')],
            },
        ),
    ]
