# Generated by Django 5.2.14 on 2026-08-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0002_datapointmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frameworknode',
            options={'ordering': ['framework_version', 'path', 'display_order', 'code']},
        ),
        migrations.AddConstraint(
            model_name='frameworkversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('framework',), name='uq_default_framework_version'),
        ),
    ]
