# Generated by Django 5.2.14 on 2026-08-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0003_alter_frameworknode_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='frameworkversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_from__isnull', True), ('effective_to__isnull', True), ('effective_from__lte', models.F('effective_to')), _connector='OR'), name='ck_fw_version_effective_date_range'),
        ),
        migrations.AddConstraint(
            model_name='frameworkversion',
            constraint=models.CheckConstraint(condition=models.Q(('published_at__isnull', True), ('effective_from__isnull', True), ('published_at__lte', models.F('effective_from')), _connector='OR'), name='ck_fw_version_publication_date'),
        ),
        migrations.AddConstraint(
            model_name='frameworkversion',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('is_active', True), _connector='OR'), name='ck_fw_version_default_active'),
        ),
    ]
