# Generated by Django 5.2.14 on 2026-08-25 11:46

import apps.core.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datapoints', '0003_alter_unit_factor_to_base'),
        ('materiality', '0004_materialityassessment_reporting_period_required'),
        ('organizations', '0002_remove_facility_department_remove_facility_city_and_more'),
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('material_subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='materiality.materialsubtopic')),
                ('material_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='materiality.materialtopic')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_goals', to=settings.AUTH_USER_MODEL)),
                ('source_assessment_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='materiality.assessmenttopic')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metric_source_type', models.CharField(choices=[('DATAPOINT', 'Canonical M4 datapoint'), ('CALCULATED_METRIC', 'Calculated metric'), ('MANUAL_REFERENCE', 'Manual/reference metric')], max_length=30)),
                ('metric_code', models.CharField(blank=True, default='', max_length=150)),
                ('direction', models.CharField(choices=[('REDUCE', 'Reduce'), ('INCREASE', 'Increase'), ('MAINTAIN', 'Maintain')], max_length=20)),
                ('aggregation', models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average'), ('LATEST', 'Latest'), ('COUNT', 'Count'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('datapoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpis', to='datapoints.datapoint')),
                ('default_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpis', to='datapoints.unit')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='targets.goal')),
                ('unit_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpis', to='datapoints.unitfamily')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KPIInitiative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETE', 'Complete'), ('PARKED', 'Parked')], default='PLANNED', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('anticipated_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='targets.kpi')),
                ('org_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpi_initiatives', to='organizations.orgnode')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_kpi_initiatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'name'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('baseline_source', models.CharField(choices=[('SYSTEM_DATA', 'Approved system data'), ('REFERENCE', 'Reference/manual')], default='REFERENCE', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('target_type', models.CharField(choices=[('ABSOLUTE', 'Absolute'), ('INTENSITY', 'Intensity'), ('PERCENTAGE', 'Percentage')], default='ABSOLUTE', max_length=20)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('MISSED', 'Missed'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('basis', models.CharField(choices=[('PRIOR_YEAR_ACTUAL', 'Prior-year actual'), ('PRIOR_REPORT', 'Prior report'), ('PEER_BENCHMARK', 'Peer benchmark'), ('REGULATORY_REQUIREMENT', 'Regulatory requirement'), ('INDUSTRY_STANDARD', 'Industry standard'), ('SCIENCE_BASED', 'Science based'), ('CUSTOMER_REQUIREMENT', 'Customer requirement'), ('MANAGEMENT_COMMITMENT', 'Management commitment'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('source_reference', models.CharField(blank=True, default='', max_length=500)),
                ('methodology', models.TextField(blank=True, default='')),
                ('rationale', models.TextField(blank=True, default='')),
                ('baseline_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_baselines', to='periods.reportingperiod')),
                ('baseline_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_baselines', to='datapoints.unit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_targets', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='targets.kpi')),
                ('org_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='organizations.orgnode')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_targets', to=settings.AUTH_USER_MODEL)),
                ('target_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_endpoints', to='periods.reportingperiod')),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_endpoints', to='datapoints.unit')),
            ],
            options={
                'ordering': ['-target_period__start_date', '-created_at'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['status'], name='targets_goa_status_30ef44_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['material_topic'], name='targets_goa_materia_d6281b_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['owner'], name='targets_goa_owner_i_cc6895_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.UniqueConstraint(fields=('goal', 'code'), name='uq_goal_kpi_code'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['kpi', 'status'], name='targets_tar_kpi_id_828cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['org_node'], name='targets_tar_org_nod_9fc0da_idx'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE'])), fields=('kpi', 'org_node', 'target_period'), name='uq_active_target_kpi_scope_period'),
        ),
    ]
