# Generated by Django 5.2.14 on 2026-08-26 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0003_alter_unit_factor_to_base'),
        ('organizations', '0002_remove_facility_department_remove_facility_city_and_more'),
        ('periods', '0001_initial'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('org_node__isnull', True), ('status__in', ['DRAFT', 'ACTIVE'])), fields=('kpi', 'target_period'), name='uq_active_company_target_kpi_period'),
        ),
    ]
