# Generated by Django 5.2.14 on 2026-08-27 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_city_created_at_city_updated_at_country_created_at_and_more'),
        ('datapoints', '0003_alter_unit_factor_to_base'),
        ('organizations', '0002_remove_facility_department_remove_facility_city_and_more'),
        ('periods', '0001_initial'),
        ('targets', '0002_strengthen_target_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('org_node__isnull', False), ('status__in', ['DRAFT', 'ACTIVE'])), fields=('kpi', 'org_node'), name='uq_editable_target_kpi_org_scope'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('org_node__isnull', True), ('status__in', ['DRAFT', 'ACTIVE'])), fields=('kpi',), name='uq_editable_company_target_kpi'),
        ),
    ]
