# Generated by Django 5.2.14 on 2026-08-24 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notification_notificatio_recipie_201701_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_read", False), ("read_at__isnull", True)),
                    models.Q(("is_read", True), ("read_at__isnull", False)),
                    _connector="OR",
                ),
                name="notification_read_state_consistent",
            ),
        ),
    ]
