from django.urls import path

from .views import (
    CollectionCampaignBulkReassignAPIView,
    CollectionCampaignCloseAPIView,
    CollectionCampaignDetailAPIView,
    CollectionCampaignGenerateAPIView,
    CollectionCampaignListCreateAPIView,
    CollectionCampaignProgressAPIView,
    CollectionCampaignTargetListAPIView,
    DataRequestDetailAPIView,
    DataRequestListCreateAPIView,
    DataRequestReassignAPIView,
    EvidenceDetailAPIView,
    EvidenceDownloadAPIView,
    EvidenceListUploadAPIView,
    MyDataRequestListAPIView,
    SubmissionAnswerAPIView,
    SubmissionApproveAPIView,
    SubmissionDetailAPIView,
    SubmissionHistoryAPIView,
    SubmissionRejectAPIView,
    SubmissionReopenAPIView,
    SubmissionSubmitAPIView,
    SubmissionTableRowDetailAPIView,
    SubmissionTableRowsAPIView,
)

app_name = "data_capture"

urlpatterns = [
    path("campaigns/", CollectionCampaignListCreateAPIView.as_view(), name="campaign-list"),
    path("campaigns/<uuid:campaign_id>/", CollectionCampaignDetailAPIView.as_view(), name="campaign-detail"),
    path("campaigns/<uuid:campaign_id>/targets/", CollectionCampaignTargetListAPIView.as_view(), name="campaign-targets"),
    path("campaigns/<uuid:campaign_id>/generate/", CollectionCampaignGenerateAPIView.as_view(), name="campaign-generate"),
    path("campaigns/<uuid:campaign_id>/progress/", CollectionCampaignProgressAPIView.as_view(), name="campaign-progress"),
    path("campaigns/<uuid:campaign_id>/bulk-reassign/", CollectionCampaignBulkReassignAPIView.as_view(), name="campaign-bulk-reassign"),
    path("campaigns/<uuid:campaign_id>/close/", CollectionCampaignCloseAPIView.as_view(), name="campaign-close"),
    path("requests/", DataRequestListCreateAPIView.as_view(), name="request-list"),
    path("requests/mine/", MyDataRequestListAPIView.as_view(), name="request-mine"),
    path("requests/<uuid:request_id>/", DataRequestDetailAPIView.as_view(), name="request-detail"),
    path("requests/<uuid:request_id>/reassign/", DataRequestReassignAPIView.as_view(), name="request-reassign"),
    path("requests/<uuid:request_id>/submission/", SubmissionDetailAPIView.as_view(), name="submission-detail"),
    path("requests/<uuid:request_id>/submission/answer/", SubmissionAnswerAPIView.as_view(), name="submission-answer"),
    path("requests/<uuid:request_id>/submission/table-rows/", SubmissionTableRowsAPIView.as_view(), name="submission-table-rows"),
    path("requests/<uuid:request_id>/submission/table-rows/<uuid:row_id>/", SubmissionTableRowDetailAPIView.as_view(), name="submission-table-row-detail"),
    path("requests/<uuid:request_id>/submission/history/", SubmissionHistoryAPIView.as_view(), name="submission-history"),
    path("requests/<uuid:request_id>/evidence/", EvidenceListUploadAPIView.as_view(), name="evidence-list"),
    path("requests/<uuid:request_id>/evidence/<uuid:evidence_id>/", EvidenceDetailAPIView.as_view(), name="evidence-detail"),
    path("requests/<uuid:request_id>/evidence/<uuid:evidence_id>/download/", EvidenceDownloadAPIView.as_view(), name="evidence-download"),
    path("requests/<uuid:request_id>/submission/submit/", SubmissionSubmitAPIView.as_view(), name="submission-submit"),
    path("requests/<uuid:request_id>/submission/approve/", SubmissionApproveAPIView.as_view(), name="submission-approve"),
    path("requests/<uuid:request_id>/submission/reject/", SubmissionRejectAPIView.as_view(), name="submission-reject"),
    path("requests/<uuid:request_id>/submission/reopen/", SubmissionReopenAPIView.as_view(), name="submission-reopen"),
]
