# Generated by Django 5.2.14 on 2026-08-18 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modules", "0004_canonicalize_module_codes_and_core_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable machine-readable unit code.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "factor_to_base",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Multiplication factor used to convert this unit to the family base unit.",
                        max_digits=20,
                    ),
                ),
                (
                    "is_base_unit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the base unit for its unit family.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["family", "name"],
            },
        ),
        migrations.CreateModel(
            name="UnitFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable machine-readable unit family code.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DatapointCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable machine-readable category code.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "esg_pillar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("E", "E"),
                            ("S", "S"),
                            ("G", "G"),
                            ("PLATFORM", "Platform"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "module",
                    models.ForeignKey(
                        db_column="module_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datapoint_categories",
                        to="modules.module",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Datapoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=200, unique=True)),
                ("label", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("DECIMAL", "Decimal"),
                            ("INTEGER", "Integer"),
                            ("TEXT", "Text"),
                            ("LONG_TEXT", "Long Text"),
                            ("BOOLEAN", "Boolean"),
                            ("SELECT", "Select"),
                            ("DATE", "Date"),
                            ("TABLE", "Table"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "collection_level",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company"),
                            ("ORG_NODE", "Org Node"),
                            ("FACILITY", "Facility"),
                            ("ANY", "Any"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "module",
                    models.ForeignKey(
                        db_column="module_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datapoints",
                        to="modules.module",
                        to_field="code",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datapoints",
                        to="datapoints.datapointcategory",
                    ),
                ),
                (
                    "default_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_datapoints",
                        to="datapoints.unit",
                    ),
                ),
                (
                    "unit_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datapoints",
                        to="datapoints.unitfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="unit",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="datapoints.unitfamily",
            ),
        ),
        migrations.CreateModel(
            name="DatapointTableColumn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("DECIMAL", "Decimal"),
                            ("INTEGER", "Integer"),
                            ("TEXT", "Text"),
                            ("LONG_TEXT", "Long Text"),
                            ("BOOLEAN", "Boolean"),
                            ("SELECT", "Select"),
                            ("DATE", "Date"),
                            ("TABLE", "Table"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "datapoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_columns",
                        to="datapoints.datapoint",
                    ),
                ),
                (
                    "default_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_table_columns",
                        to="datapoints.unit",
                    ),
                ),
                (
                    "unit_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="table_columns",
                        to="datapoints.unitfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="DatapointOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "datapoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="datapoints.datapoint",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("datapoint", "code"),
                        name="unique_datapoint_option_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DatapointTableRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "datapoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_rows",
                        to="datapoints.datapoint",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("datapoint", "code"), name="unique_table_row_code"
                    ),
                    models.UniqueConstraint(
                        fields=("datapoint", "display_order"),
                        name="unique_table_row_order",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_base_unit", True)),
                fields=("family",),
                name="unique_unit_per_family",
            ),
        ),
        migrations.AddConstraint(
            model_name="datapointtablecolumn",
            constraint=models.UniqueConstraint(
                fields=("datapoint", "code"), name="unique_table_column_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="datapointtablecolumn",
            constraint=models.UniqueConstraint(
                fields=("datapoint", "display_order"), name="unique_table_column_order"
            ),
        ),
    ]
