# Generated by Django 5.2.14 on 2026-08-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datapoints", "0002_datapoint_table_contract_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="factor_to_base",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Multiplication factor used to convert this unit to the family base unit.",
                max_digits=30,
            ),
        ),
    ]
