# Generated by Django 5.2.14 on 2026-08-11 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_city_created_at_city_updated_at_country_created_at_and_more'),
        ('materiality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('financial_year', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('mode', models.CharField(choices=[('IMPACT', 'Impact Materiality'), ('FINANCIAL', 'Financial Materiality'), ('DOUBLE', 'Double Materiality')], default='DOUBLE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('primary_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('secondary_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scale_min', models.IntegerField(default=1)),
                ('scale_max', models.IntegerField(default=5)),
                ('internal_blend_weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_materiality_assessments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiality_assessments', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_materiality_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materiality_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_included', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('primary_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('secondary_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classification', models.CharField(blank=True, max_length=50)),
                ('is_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiality_topic_overrides', to=settings.AUTH_USER_MODEL)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_topics', to='materiality.materialsubtopic')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_topics', to='materiality.materialityassessment')),
            ],
            options={
                'db_table': 'assessment_topic',
                'ordering': ['display_order'],
            },
        ),
    ]
