# Generated by Django 5.2.14 on 2026-08-18 06:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_reporting_periods(apps, schema_editor):
    """Preserve the 0002 date-based assessments during the platform transition."""
    Assessment = apps.get_model("materiality", "MaterialityAssessment")
    ReportingPeriod = apps.get_model("periods", "ReportingPeriod")
    for assessment in Assessment.objects.all().iterator():
        period = ReportingPeriod.objects.filter(
            start_date=assessment.period_start,
            end_date=assessment.period_end,
        ).first()
        if period is None:
            period = ReportingPeriod.objects.create(
                name=assessment.financial_year or f"Materiality {assessment.period_start:%Y}",
                period_type="ANNUAL",
                start_date=assessment.period_start,
                end_date=assessment.period_end,
                status="OPEN",
                is_active=True,
            )
        assessment.reporting_period_id = period.pk
        if assessment.mode in {"IMPACT", "FINANCIAL"}:
            assessment.mode = "SINGLE"
        assessment.save(update_fields=["reporting_period", "mode"])


class Migration(migrations.Migration):

    dependencies = [
        ('materiality', '0002_materialityassessment_assessmenttopic'),
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impact_type', models.CharField(choices=[('ACTUAL', 'Actual'), ('POTENTIAL', 'Potential')], max_length=20)),
                ('scale', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('scope', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('irremediability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('likelihood', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('financial_magnitude', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('financial_likelihood', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rationale', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'internal_score',
            },
        ),
        migrations.CreateModel(
            name='ScaleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.CharField(choices=[('IMPACT', 'Impact'), ('STAKEHOLDER_IMPORTANCE', 'Stakeholder Importance'), ('FINANCIAL', 'Financial')], max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'scale_definition',
            },
        ),
        migrations.CreateModel(
            name='ScaleOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'scale_option',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=20)),
                ('thresholds_snapshot', models.JSONField()),
                ('group_weights_snapshot', models.JSONField()),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('invited_count', models.PositiveIntegerField(default=0)),
                ('method_version', models.CharField(max_length=50)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'score_run',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRunTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('secondary_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classification', models.CharField(max_length=30)),
                ('is_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('group_breakdown', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'score_run_topic',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'stakeholder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_internal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'stakeholder_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('closing_text', models.TextField(blank=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
            ],
            options={
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyGroupLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'survey_group_link',
            },
        ),
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('SUBMITTED', 'Submitted')], default='NOT_SENT', max_length=20)),
            ],
            options={
                'db_table': 'survey_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.CharField(choices=[('IMPACT', 'Impact'), ('STAKEHOLDER_IMPORTANCE', 'Stakeholder Importance'), ('FINANCIAL', 'Financial')], max_length=50)),
                ('question_text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'survey_question',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey_response',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('IDENTIFIED', 'Identified invitation'), ('ANONYMOUS', 'Anonymous group link')], max_length=20)),
                ('response_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey_submission',
            },
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='reporting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiality_assessments', to='periods.reportingperiod'),
        ),
        migrations.RunPython(assign_reporting_periods, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='materialityassessment',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='materialityassessment',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='materialityassessment',
            name='period_start',
        ),
        migrations.AlterField(
            model_name='materialityassessment',
            name='mode',
            field=models.CharField(choices=[('SINGLE', 'Single Materiality'), ('DOUBLE', 'Double Materiality')], default='DOUBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialityassessment',
            name='primary_threshold',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='materialityassessment',
            name='secondary_threshold',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='materialityassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('SCORED', 'Scored')], default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assessmenttopic',
            constraint=models.UniqueConstraint(fields=('assessment', 'subtopic'), name='unique_assessment_subtopic'),
        ),
        migrations.AddField(
            model_name='internalscore',
            name='assessment_topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_score', to='materiality.assessmenttopic'),
        ),
        migrations.AddField(
            model_name='internalscore',
            name='scored_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_materiality_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scaledefinition',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale_definitions', to='materiality.materialityassessment'),
        ),
        migrations.AddField(
            model_name='scaleoption',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='materiality.scaledefinition'),
        ),
        migrations.AddField(
            model_name='scorerun',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_runs', to='materiality.materialityassessment'),
        ),
        migrations.AddField(
            model_name='scorerun',
            name='run_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiality_score_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoreruntopic',
            name='assessment_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_run_results', to='materiality.assessmenttopic'),
        ),
        migrations.AddField(
            model_name='scoreruntopic',
            name='score_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_results', to='materiality.scorerun'),
        ),
        migrations.AddField(
            model_name='stakeholdergroup',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_groups', to='materiality.materialityassessment'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='materiality.stakeholdergroup'),
        ),
        migrations.AddField(
            model_name='survey',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='materiality.materialityassessment'),
        ),
        migrations.AddField(
            model_name='surveygrouplink',
            name='stakeholder_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_links', to='materiality.stakeholdergroup'),
        ),
        migrations.AddField(
            model_name='surveygrouplink',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='materiality.survey'),
        ),
        migrations.AddField(
            model_name='surveyinvitation',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_invitations', to='materiality.stakeholder'),
        ),
        migrations.AddField(
            model_name='surveyinvitation',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='materiality.survey'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='assessment_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='materiality.assessmenttopic'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_questions', to='materiality.scaledefinition'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='materiality.survey'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='materiality.surveyinvitation'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='materiality.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='materiality.surveyinvitation'),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='stakeholder_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_submissions', to='materiality.stakeholdergroup'),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='materiality.survey'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='materiality.surveysubmission'),
        ),
        migrations.AddConstraint(
            model_name='scaleoption',
            constraint=models.UniqueConstraint(fields=('scale', 'value'), name='unique_scale_option_value'),
        ),
        migrations.AddConstraint(
            model_name='scoreruntopic',
            constraint=models.UniqueConstraint(fields=('score_run', 'assessment_topic'), name='unique_score_run_assessment_topic'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.UniqueConstraint(fields=('group', 'email'), name='unique_stakeholder_email_per_group'),
        ),
        migrations.AddConstraint(
            model_name='surveygrouplink',
            constraint=models.UniqueConstraint(fields=('survey', 'stakeholder_group'), name='unique_survey_stakeholder_group_link'),
        ),
        migrations.AddConstraint(
            model_name='surveyinvitation',
            constraint=models.UniqueConstraint(fields=('survey', 'stakeholder'), name='unique_survey_stakeholder_invitation'),
        ),
        migrations.AddConstraint(
            model_name='surveysubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invitation__isnull', False), ('source', 'IDENTIFIED')), models.Q(('invitation__isnull', True), ('source', 'ANONYMOUS')), _connector='OR'), name='survey_submission_source_matches_invitation'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('invitation', 'question'), name='unique_invitation_question_response'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_submission_question_response'),
        ),
    ]
