# Generated by Django 5.2.14 on 2026-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("MODULE_ACCESS", "Module Access"),
                            ("CREATE", "Create"),
                            ("EDIT", "Edit"),
                            ("VIEW", "View"),
                            ("DELETE", "Delete"),
                            ("APPROVE", "Approve"),
                            ("CLOSE", "Close"),
                            ("MANAGE", "Manage"),
                            ("EXPORT", "Export"),
                        ],
                        default="VIEW",
                        help_text="Type of permission",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order to display in UI (lower = first)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["name", "display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_code", models.CharField(max_length=30, unique=True)),
                ("role_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="accounts.permissions"
                    ),
                ),
            ],
        ),
    ]
