# Generated by Django 5.2.14 on 2026-08-10 04:46

import apps.core.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permissions_role'),
        ('companies', '0003_city_created_at_city_updated_at_country_created_at_and_more'),
        ('organizations', '0002_remove_facility_department_remove_facility_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('module_code', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('MODULE_ACCESS', 'Module Access'), ('CREATE', 'Create'), ('EDIT', 'Edit'), ('VIEW', 'View'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('CLOSE', 'Close'), ('MANAGE', 'Manage'), ('EXPORT', 'Export')], help_text='Type of permission', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in UI (lower = first)')),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['display_order', 'name'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='assigned_roles', to='accounts.permission'),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_department',
                'ordering': ['user'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(blank=True, help_text='Null means access to all modules', max_length=100, null=True)),
                ('framework_code', models.CharField(blank=True, help_text='Null means access to all frameworks', max_length=100, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_role_assignments',
                'ordering': ['user', 'role'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role_name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_company_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System roles are seeded and cannot be deleted'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_code',
            field=models.CharField(help_text='Unique code for the role', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(help_text='Display name of the role', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='permissions_code_a0a529_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module_code'], name='permissions_module__7ecf17_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_code'], name='roles_role_co_be68ba_idx'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='companies.department'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='org_node',
            field=models.ForeignKey(blank=True, help_text='Null means company-wide access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='organizations.orgnode'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userdepartment',
            index=models.Index(fields=['user'], name='user_depart_user_id_772bc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdepartment',
            constraint=models.UniqueConstraint(fields=('user', 'department'), name='unique_user_department'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user'], name='user_role_a_user_id_7d6d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['role'], name='user_role_a_role_id_867142_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['org_node'], name='user_role_a_org_nod_7282b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'org_node', 'module_code', 'framework_code'), name='unique_role_assignment'),
        ),
    ]
