# Generated by Django 5.2.14 on 2026-07-30 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("iso_code", models.CharField(max_length=5, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["iso_code"], name="companies_c_iso_cod_9bdbcf_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="companies.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("state_code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="companies.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("company_code", models.CharField(max_length=20, unique=True)),
                ("company_name", models.CharField(max_length=255)),
                ("gst_number", models.CharField(blank=True, max_length=50, null=True)),
                ("cin_number", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_incorporation", models.DateField(blank=True, null=True)),
                ("about_company", models.TextField(blank=True, null=True)),
                (
                    "company_password_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                (
                    "billing_zip_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("contact_person", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_number", models.CharField(max_length=15)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "listed_company",
                    models.BooleanField(
                        default=False,
                        help_text="True if the company is listed on a stock exchange.",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last login time of the company admin",
                        null=True,
                        verbose_name="Admin Last Login",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="companies.city",
                    ),
                ),
                (
                    "billing_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="companies.country",
                    ),
                ),
                (
                    "billing_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="companies.state",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="companies.state",
            ),
        ),
        migrations.AddIndex(
            model_name="state",
            index=models.Index(
                fields=["country"], name="companies_s_country_b55143_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="state",
            index=models.Index(
                fields=["state_code"], name="companies_s_state_c_9cf305_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("country", "name"), ("country", "state_code")},
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["country"], name="companies_c_country_1adac4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["state"], name="companies_c_state_i_8e0a86_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("country", "state", "name")},
        ),
    ]
