# Generated by Django 5.2.14 on 2026-08-05 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company__company_name', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='billing_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='billing_address',
            new_name='corporate_address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='billing_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='billing_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='billing_zip_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_password_hash',
        ),
        migrations.RemoveField(
            model_name='company',
            name='last_login',
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='financial_year_start_month',
            field=models.PositiveSmallIntegerField(default=4, help_text='1=January ... 12=December'),
        ),
        migrations.AddField(
            model_name='company',
            name='ownership_form',
            field=models.CharField(blank=True, help_text='Private, Public, Government, Partnership, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='paid_up_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stock_exchanges',
            field=models.CharField(blank=True, help_text='Comma separated stock exchanges.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='listed_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_code'], name='companies_c_company_ffc830_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='companies_c_company_14f39a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='companies.department'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company'], name='companies_d_company_c31b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'name'], name='companies_d_company_e28d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'code'], name='companies_d_company_fef462_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_department'], name='companies_d_parent__fd921f_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_department_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_department_code_per_company'),
        ),
    ]
