# Generated by Django 5.2.14 on 2026-08-12 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "esg_pillar",
                    models.CharField(
                        choices=[
                            ("E", "E"),
                            ("S", "S"),
                            ("G", "G"),
                            ("Platform", "Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("is_core", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "modules",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
