# Generated by Django 5.2.14 on 2026-08-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="code",
            field=models.CharField(
                help_text="Stable machine-readable module identifier.",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="module",
            name="esg_pillar",
            field=models.CharField(
                choices=[
                    ("E", "Environmental"),
                    ("S", "Social"),
                    ("G", "Governance"),
                    ("PLATFORM", "Platform"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="module",
            name="is_core",
            field=models.BooleanField(
                default=False, help_text="Core modules cannot be disabled."
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether this module is enabled in this deployment.",
            ),
        ),
        migrations.AlterModelTable(
            name="module",
            table=None,
        ),
    ]
