# Generated by Django 5.2.14 on 2026-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_alter_module_code_alter_module_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="esg_pillar",
            field=models.CharField(
                choices=[("E", "E"), ("S", "S"), ("G", "G"), ("PLATFORM", "Platform")],
                default="PLATFORM",
                max_length=10,
            ),
        ),
    ]
