# Generated by Django 5.2.14 on 2026-08-21 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datapoints", "0002_datapoint_table_contract_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable machine-readable calculation rule code.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "rule_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Declarative calculation configuration. Must contain metadata only and must not execute arbitrary code.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "datapoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional M4 datapoint to which this calculation rule applies.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_rules",
                        to="datapoints.datapoint",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EmissionFactorSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable machine-readable source/factor-set code.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the factor source or set.",
                        max_length=255,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        help_text="Organization or authority that published the source.",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Source or factor-set version.", max_length=100
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Publication, document, dataset, or reference identifier.",
                        max_length=255,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"),
                        name="unique_emission_factor_source_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable machine-readable emission factor code.",
                        max_length=150,
                    ),
                ),
                (
                    "activity_key",
                    models.CharField(
                        help_text="Stable key identifying the activity or factor category for which this factor applies.",
                        max_length=150,
                    ),
                ),
                (
                    "factor_value",
                    models.DecimalField(
                        decimal_places=15,
                        help_text="Decimal-safe emission factor value.",
                        max_digits=30,
                    ),
                ),
                (
                    "geography",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional geography/applicability identifier used during factor selection.",
                        max_length=100,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Traceability or source-specific notes.",
                    ),
                ),
                (
                    "input_unit",
                    models.ForeignKey(
                        help_text="Canonical M4 unit in which the activity quantity is supplied.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emission_factor_inputs",
                        to="datapoints.unit",
                    ),
                ),
                (
                    "output_unit",
                    models.ForeignKey(
                        help_text="Canonical M4 unit produced by the factor calculation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emission_factor_outputs",
                        to="datapoints.unit",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factors",
                        to="calculations.emissionfactorsource",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "code"), name="unique_factor_code_per_source"
                    )
                ],
            },
        ),
    ]
