# Generated by Django 5.2.14 on 2026-08-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculationrule",
            name="rule_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Declarative calculation-rule metadata. Must contain operation, input and factor as strings. Must not contain executable code or arbitrary expressions.",
            ),
        ),
    ]
