# Generated by Django 5.2.14 on 2026-08-25 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0002_alter_calculationrule_rule_metadata"),
        ("data_capture", "0002_alter_evidencefile_answer"),
        ("datapoints", "0003_alter_unit_factor_to_base"),
        (
            "organizations",
            "0002_remove_facility_department_remove_facility_city_and_more",
        ),
        ("periods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_quantity",
                    models.DecimalField(
                        decimal_places=15,
                        help_text="Original numeric quantity captured in the approved Answer.",
                        max_digits=30,
                    ),
                ),
                (
                    "normalized_quantity",
                    models.DecimalField(
                        decimal_places=15,
                        help_text="Input quantity normalized to the factor input unit.",
                        max_digits=30,
                    ),
                ),
                (
                    "factor_value",
                    models.DecimalField(
                        decimal_places=15,
                        help_text="Exact factor value used by this calculation.",
                        max_digits=30,
                    ),
                ),
                (
                    "factor_source_code",
                    models.CharField(
                        help_text="Snapshot of the factor source code.", max_length=100
                    ),
                ),
                (
                    "factor_source_name",
                    models.CharField(
                        help_text="Snapshot of the factor source name.", max_length=255
                    ),
                ),
                (
                    "factor_source_version",
                    models.CharField(
                        help_text="Snapshot of the factor source version.",
                        max_length=100,
                    ),
                ),
                (
                    "factor_source_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the factor source reference.",
                        max_length=255,
                    ),
                ),
                (
                    "factor_code",
                    models.CharField(
                        help_text="Snapshot of the selected emission factor code.",
                        max_length=150,
                    ),
                ),
                (
                    "activity_key",
                    models.CharField(
                        help_text="Activity key used during factor selection.",
                        max_length=150,
                    ),
                ),
                (
                    "geography",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Geography used during factor selection.",
                        max_length=100,
                    ),
                ),
                (
                    "calculation_date",
                    models.DateField(help_text="Date used for factor applicability."),
                ),
                (
                    "calculated_value",
                    models.DecimalField(
                        decimal_places=15,
                        help_text="Calculated Decimal-safe result.",
                        max_digits=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CURRENT", "Current"), ("SUPERSEDED", "Superseded")],
                        default="CURRENT",
                        max_length=20,
                    ),
                ),
                (
                    "calculation_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version of the calculation for the same approved Answer.",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        help_text="Approved M5 Answer used as the calculation input.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to="data_capture.answer",
                    ),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "calculation_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to="calculations.calculationrule",
                    ),
                ),
                (
                    "data_request",
                    models.ForeignKey(
                        help_text="M5 DataRequest associated with the calculation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to="data_capture.datarequest",
                    ),
                ),
                (
                    "datapoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to="datapoints.datapoint",
                    ),
                ),
                (
                    "emission_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to="calculations.emissionfactor",
                    ),
                ),
                (
                    "input_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_result_inputs",
                        to="datapoints.unit",
                    ),
                ),
                (
                    "org_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to="organizations.orgnode",
                    ),
                ),
                (
                    "output_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_result_outputs",
                        to="datapoints.unit",
                    ),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to="periods.reportingperiod",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="M5 Submission containing the source Answer.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculation_results",
                        to="data_capture.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["answer", "status"],
                        name="calculation_answer__972b09_idx",
                    ),
                    models.Index(
                        fields=["submission", "status"],
                        name="calculation_submiss_c0626c_idx",
                    ),
                    models.Index(
                        fields=["datapoint", "org_node", "reporting_period"],
                        name="calculation_datapoi_4c424c_idx",
                    ),
                    models.Index(
                        fields=["calculation_rule"],
                        name="calculation_calcula_f7f516_idx",
                    ),
                    models.Index(
                        fields=["emission_factor"],
                        name="calculation_emissio_f87648_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("answer", "calculation_version"),
                        name="unique_answer_calculation_version",
                    )
                ],
            },
        ),
    ]
