# Generated by Django 5.2.14 on 2026-08-21 05:27

import apps.core.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datapoints', '0002_datapoint_table_contract_metadata'),
        ('organizations', '0002_remove_facility_department_remove_facility_city_and_more'),
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('integer_value', models.BigIntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_data_capture_answers', to=settings.AUTH_USER_MODEL)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datapoints.datapointoption')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datapoints.unit')),
            ],
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnswerTableRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='data_capture.answer')),
                ('definition_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datapoints.datapointtablerow')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnswerTableCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('integer_value', models.BigIntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datapoints.datapointtablecolumn')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datapoints.datapointoption')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datapoints.unit')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='data_capture.answertablerow')),
            ],
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(editable=False, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('instructions', models.TextField(blank=True, default='')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_data_requests', to=settings.AUTH_USER_MODEL)),
                ('datapoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to='datapoints.datapoint')),
                ('org_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to='organizations.orgnode')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to='periods.reportingperiod')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DataRequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_request_events', to=settings.AUTH_USER_MODEL)),
                ('data_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data_capture.datarequest')),
                ('previous_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_data_request_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_data_capture_submissions', to=settings.AUTH_USER_MODEL)),
                ('data_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='data_capture.datarequest')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_data_capture_submissions', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopened_data_capture_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_data_capture_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='data_capture/evidence/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='data_capture.answer')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_data_capture_evidence', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='data_capture.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='data_capture.submission'),
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('DRAFT_SAVED', 'Draft saved'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REOPENED', 'Reopened')], max_length=20)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='', max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data_capture.submission')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='answertablerow',
            constraint=models.UniqueConstraint(condition=models.Q(('definition_row__isnull', False)), fields=('answer', 'definition_row'), name='uq_answer_table_fixed_row'),
        ),
        migrations.AddConstraint(
            model_name='answertablerow',
            constraint=models.UniqueConstraint(fields=('answer', 'display_order'), name='uq_answer_table_row_order'),
        ),
        migrations.AddIndex(
            model_name='answertablecell',
            index=models.Index(fields=['decimal_value'], name='data_captur_decimal_322e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='answertablecell',
            index=models.Index(fields=['integer_value'], name='data_captur_integer_6bb7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='answertablecell',
            index=models.Index(fields=['date_value'], name='data_captur_date_va_2dcb58_idx'),
        ),
        migrations.AddConstraint(
            model_name='answertablecell',
            constraint=models.UniqueConstraint(fields=('row', 'column'), name='uq_answer_table_cell'),
        ),
        migrations.AddIndex(
            model_name='datarequest',
            index=models.Index(fields=['assignee', 'status'], name='data_captur_assigne_60a8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='datarequest',
            index=models.Index(fields=['org_node', 'reporting_period'], name='data_captur_org_nod_3f6884_idx'),
        ),
        migrations.AddIndex(
            model_name='datarequest',
            index=models.Index(fields=['module_code'], name='data_captur_module__84ccd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='datarequest',
            constraint=models.UniqueConstraint(fields=('datapoint', 'org_node', 'reporting_period'), name='uq_data_request_datapoint_org_period'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='data_captur_status_694ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['submission'], name='data_captur_submiss_7577e9_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['decimal_value'], name='data_captur_decimal_44e2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['integer_value'], name='data_captur_integer_718d21_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['date_value'], name='data_captur_date_va_8a60a0_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['selected_option'], name='data_captur_selecte_ec093e_idx'),
        ),
    ]
