# Generated by Django 5.2.14 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_capture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidencefile",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_files",
                to="data_capture.answer",
            ),
        ),
    ]
