# Generated by Django 5.2.14 on 2026-08-24 11:21

import apps.core.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_city_created_at_city_updated_at_country_created_at_and_more'),
        ('data_capture', '0002_alter_evidencefile_answer'),
        ('datapoints', '0003_alter_unit_factor_to_base'),
        ('organizations', '0002_remove_facility_department_remove_facility_city_and_more'),
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_due_date', models.DateField(blank=True, null=True)),
                ('default_instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_campaigns', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_collection_campaigns', to=settings.AUTH_USER_MODEL)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_campaigns', to='periods.reportingperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(apps.core.mixins.ActivityLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, default='')),
                ('request_outcome', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('EXISTING', 'Existing/reused')], default='', max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_targets', to=settings.AUTH_USER_MODEL)),
                ('data_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_targets', to='data_capture.datarequest')),
                ('datapoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_targets', to='datapoints.datapoint')),
                ('org_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_targets', to='organizations.orgnode')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='data_capture.collectioncampaign')),
            ],
            options={
                'ordering': ['datapoint__code', 'org_node__path'],
            },
        ),
        migrations.CreateModel(
            name='CollectionCampaignEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('GENERATED', 'Requests generated'), ('REASSIGNED', 'Requests reassigned'), ('CLOSED', 'Closed')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data_capture.collectioncampaign')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='collectioncampaign',
            index=models.Index(fields=['company', 'reporting_period'], name='data_captur_company_de50fb_idx'),
        ),
        migrations.AddIndex(
            model_name='collectioncampaign',
            index=models.Index(fields=['status'], name='data_captur_status_6f0376_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['campaign', 'org_node'], name='data_captur_campaig_10506a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['data_request'], name='data_captur_data_re_b630b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigntarget',
            constraint=models.UniqueConstraint(fields=('campaign', 'datapoint', 'org_node'), name='uq_campaign_target_datapoint_org'),
        ),
    ]
