# Generated by Django 5.2.14 on 2026-08-05 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_department_alter_company_options_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='department',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='city',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='country',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='state',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='company',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='state',
        ),
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('LEGAL_ENTITY', 'Legal Entity'), ('BUSINESS_UNIT', 'Business Unit'), ('DIVISION', 'Division'), ('REGION', 'Region'), ('FACILITY', 'Facility')], max_length=30)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('depth', models.PositiveIntegerField(default=0, editable=False)),
                ('path', models.CharField(editable=False, max_length=1000)),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('grid_region', models.CharField(blank=True, max_length=100, null=True)),
                ('water_stressed_area', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('operational_control', models.BooleanField(default=True)),
                ('consolidation_method', models.CharField(choices=[('FULL', 'Full'), ('PROPORTIONAL', 'Proportional'), ('EQUITY', 'Equity')], default='FULL', max_length=20)),
                ('commissioned_on', models.DateField(blank=True, null=True)),
                ('decommissioned_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_nodes', to='companies.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_nodes', to='companies.company')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_nodes', to='companies.country')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.orgnode')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_nodes', to='companies.state')),
            ],
            options={
                'ordering': ['company__company_name', 'depth', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['company'], name='organizatio_company_5c02e4_idx'),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['parent'], name='organizatio_parent__91f1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['node_type'], name='organizatio_node_ty_d7c1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['path'], name='organizatio_path_240958_idx'),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['depth'], name='organizatio_depth_9038d0_idx'),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_b3928c_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_orgnode_code_per_company'),
        ),
    ]
