# Generated by Django 5.2.14 on 2026-08-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_capture", "0003_collectioncampaign_campaigntarget_and_more"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importrow",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_rows",
                to="data_capture.answer",
            ),
        ),
    ]
